### PR TITLE
Milestone 1 Backend

### PR DESCRIPTION
**Pull request by melihaydogd**
Backend meets the milestone 1 requirements and is in working condition. It is ready to merge into master branch.

### CODE REVIEW

**Comment by mertlkn** [comment]
All our work has already been done. Everything is working fine, we can merge this into master.

**Review by zcanfes — APPROVED** [review]
We tested every feature and we are ready to merge this backend for milestone 😄 👯 🥳 🎉

**Comment by melihozcan1** [comment]
The work in the backend looks solid, it works without causing any problems.

**Review by mecolak — APPROVED** [review]
I don't know about backend work but it looks good!

**Review by omarr09 — APPROVED** [review]
Backend looks good. We can merge it

**Review by melihozcan1 — APPROVED** [review]

**Pull request merged**
