### PR TITLE
Fixed the buggy link on discovery page directing to the view post page

### PR DESCRIPTION
**Pull request by mecolak**
React router link on discovery page was crashing the application. Changed it with a redirect on clicking the button.

### CODE REVIEW

**Review by ahmetsenturk — APPROVED** [review]
Pulled this and tried it locally. Works as expected, when clicked on the popup it successfully redirects to the view post page. Kudos!

**Comment by ahmetsenturk** [comment]
As a minor modification, could you remove the popup that states the discovery button on the homepage is under maintenance?

**Comment by mecolak** [comment]
Fixed it on b259dce!

**Review by ahmetsenturk — APPROVED** [review]
Now it's perfect!

**Pull request merged**
