### PR TITLE
Milestone 1 Android

### PR DESCRIPTION
**Pull request by niyaziulke**
The Android app supports viewing posts at home page, creating posts and editing posts. Connections with backend APIs are implemented.

### CODE REVIEW

**Comment by melihozcan1** [comment]
We managed to implement every feature that we initially intended to include in our first Milestone. I believe it looks and works smoothly.

**Review by melihaydogd — APPROVED** [review]
We reviewed in today's meeting. It is good to go.

**Review by mecolak — APPROVED** [review]
Looks good to me!

**Review by melihozcan1 — APPROVED** [review]

**Review by omarr09 — APPROVED** [review]
Android looks great.

**Review by ahmetsenturk — APPROVED** [review]

**Pull request merged**
