### PR TITLE
Post story API

### PR DESCRIPTION
**Pull request by mecolak**
Could you review this request :)
Functionalities:
- API for adding posts (with POST request on /api/story). It uses a [third party API](https://tisane.ai/) for sentiment analysis.
- API for getting flagged posts (with GET request on /api/flagged_stories).
- Unit tests for above functionalities.

### CODE REVIEW

**Comment by mertlkn** [comment]
It looks and works fine. Tests are on point.

**Review by zcanfes — APPROVED** [review]
I think you have implemented the code good. The tests and views contain the necessary functionalities and are well designed.

**Review by melihaydogd — COMMENTED** [review]
Why you did not write the code in post_story.py in the views.py file? I think post story functionality can be changed. Let's talk about it in meeting.

**Review by melihozcan1 — APPROVED** [review]
Looking good.

**Review by mertlkn — APPROVED** [review]

**Review by niyaziulke — APPROVED** [review]
Everything seems fine.

**Review by omarr09 — APPROVED** [review]
Looks good to me.

**Comment by kkadirkkalkan** [comment]
Implematation of the code is nice.

**Review by kkadirkkalkan — APPROVED** [review]

**Pull request merged**
