### PR TITLE
Quotes API zcanfes

### PR DESCRIPTION
**Pull request by zcanfes**
Quotes feature is implemented. 
* Getting quotes containing the story's location name is possible. 
* Getting quotes tagged with the story's tag is possible. 
* If a quote is liked, the number of likes associated with that quote is increased and that quote is added to the database for later use in our app. 
* Tests are added and the code is tested.

### CODE REVIEW

**Review by melihaydogd — APPROVED** [review]
Tests and api functionalities looks good.

**Review by melihozcan1 — APPROVED** [review]
Looks all good to me.

**Comment by niyaziulke** [comment]
Everything seems fine. I liked the realistic mock data.

**Review by niyaziulke — APPROVED** [review]
Everything seems fine. I liked the realistic mock data.

**Review by mertlkn — APPROVED** [review]
Everything looks fine. Tests are also good.

**Review by omarr09 — APPROVED** [review]
Looks great to me. Code is well documented, and there are no apparent errors.

**Review by ahmetsenturk — APPROVED** [review]
Seems fully functional to me, good to go!

**Comment by kkadirkkalkan** [comment]
Looks good to me. Tests are also okay.

**Review by mecolak — APPROVED** [review]
Looks good!

**Review by kkadirkkalkan — APPROVED** [review]

**Pull request merged**
