### PR TITLE
City api kadir

### PR DESCRIPTION
**Pull request by kkadirkkalkan**
This API get location with latitude and longitude and finds nearby cities. It can also take parameters such as the maximum population of searched city and radius which is the maximum search distance from a location.

### CODE REVIEW

**Review by melihaydogd — APPROVED** [review]
Tests and API functionality seems good.

**Review by mertlkn — APPROVED** [review]
Tests are good, got them work. Code looks good aswell.

**Review by zcanfes — APPROVED** [review]
Tests and code look fine. The functionality is implemented and unit tests are written.

**Review by omarr09 — APPROVED** [review]
Looks great to me. I took a look at the code and it seems like there are no errors.

**Review by ahmetsenturk — APPROVED** [review]
Works just fine, good to go!

**Review by niyaziulke — APPROVED** [review]
I ran the code and tests; everything seems fine.

**Pull request merged**
