### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by mertlkn**
Frontend is complete.

### CODE REVIEW

**Review by melihaydogd — APPROVED** [review]
In meeting 18, we reviewed this work and I think it looks and works good.

**Review by zcanfes — APPROVED** [review]
We have tested and run this code in the last meeting. The homepage and the API functionalities look good on UI. The pages are clean and easily understandable. All of the API's are used. We can merge this PR :)

**Comment by kkadirkkalkan** [comment]
I reviewed frontends except mine and they seem fine.

**Review by kkadirkkalkan — APPROVED** [review]

**Review by niyaziulke — APPROVED** [review]
Pulled the code and examined it locally. It functions well and the UI is decent. 👍

**Review by omarr09 — APPROVED** [review]
UI looks simple and great. I liked it.

**Comment by mecolak** [comment]
Post viewing looks cool!

**Review by mecolak — APPROVED** [review]

**Review by ahmetsenturk — APPROVED** [review]
I reviewed the frontends, their functionalities seemed just right. It works without a problem!

**Comment by melihozcan1** [comment]
I reviewed the frontend components and it looks very pleasing to the eye and seems to be functioning really good.

**Pull request merged**
