### PR TITLE
Translation API Niyazi 

### PR DESCRIPTION
**Pull request by niyaziulke**
Translation functionality is implemented.  The API detects the source language automatically. Retrieving a translation from the database is also possible.

### CODE REVIEW

**Comment by mertlkn** [comment]
Works fine, tests covers good points.

**Comment by mecolak** [comment]
Looks good to me. API being able to detect the language automatically is a cool feature!

**Review by melihaydogd — APPROVED** [review]
I think everything is ok but I have a question. Are Translation objects are stored in the database? I did not see any save() function that is used for Translation object.

**Review by zcanfes — APPROVED** [review]
I think this functionality is a good addition to our API and application. It will make it easier for the people from different places in the world to understand each other's stories. Since this an app based on locations I think this is a necessary feature. Your code and tests look fine.

**Review by mertlkn — APPROVED** [review]

**Comment by niyaziulke** [comment]
> I think everything is ok but I have a question. Are Translation objects are stored in the database? I did not see any save() function that is used for Translation object.

You have a good point here. Normally, the user checks the translation by sending a get request, but the user is not interested in saving the translations to the database. Initially, I saved each translation to the database after a get request. Later, I learned that it's not a good practice. On the other hand, admins are still able to store some translations and in that case, the translations are retrieved from the database.

**Review by omarr09 — APPROVED** [review]
Everything seems fine here. I liked how the API functionality is tested very well.

**Review by mecolak — APPROVED** [review]

**Comment by kkadirkkalkan** [comment]
Our project needs this functionalty so it's good idea. Tests are also fine.

**Review by kkadirkkalkan — APPROVED** [review]

**Review by ahmetsenturk — APPROVED** [review]

**Pull request merged**
